#!/usr/bin/env node
const { run } = require("./tintin-helper-lib.js");

run("static-deploy", process.argv.slice(2)).catch((err) => {
  console.error(`[static-deploy] ${err && err.message ? err.message : String(err)}`);
  process.exit(1);
});
